### ISSUE TITLE
Notification not going away

### ISSUE THREAD

**Issue by ManoharOfficial** [lucasjodon/SoftWing#1]
Awesome app. I wish there was something similar that could bring up the Google keyboard on the second screen. 
Q. How do I force kill the app after I'm done playing? The notification "Select this to open controller" is not going away even after i cleared the app from recent apps.

**Comment by zoeyjodon** [comment]
Right now, there's no way to kill the notification from within the app. However, if you go to Settings->Apps->App Info->SoftWing you can Force Stop the app and the notification will go away. This will also disable the custom swivel sound feature, since that relies on the persistent notification.

Also keep in mind that this can put SoftWing into a weird state, and you might need to reenable the accesibility service and possibly restart your phone to get the app and touch service re-synched.
